"""schema inicial: cases, entidades, evidencias, relacoes, buscas, auditoria, pivos, correlacoes, conflitos

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-28 18:04:12.224279
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('component', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('canonical_value', sa.Text(), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'fingerprint', name='uq_entity_case_fingerprint')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_entities_case_type', ['case_id', 'type'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_case_id'), ['case_id'], unique=False)

    op.create_table('case_inputs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('identifier_type', sa.String(length=40), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('detection', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_inputs_case_id'), ['case_id'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('attribute', sa.String(length=80), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'entity_id', 'attribute', name='uq_conflict_attribute')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_case_id'), ['case_id'], unique=False)

    op.create_table('pivots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=True),
    sa.Column('source_entity_id', sa.String(length=32), nullable=True),
    sa.Column('target_entity_id', sa.String(length=32), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('provider_origin', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pivots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pivots_case_id'), ['case_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('source_entity_id', sa.String(length=32), nullable=False),
    sa.Column('target_entity_id', sa.String(length=32), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'fingerprint', name='uq_relationship_case_fingerprint')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_source_entity_id'), ['source_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_target_entity_id'), ['target_entity_id'], unique=False)

    op.create_table('search_executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('identifier_type', sa.String(length=40), nullable=True),
    sa.Column('identifier_value', sa.Text(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_executions_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_executions_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_executions_status'), ['status'], unique=False)

    op.create_table('correlations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('entity_a_id', sa.String(length=32), nullable=False),
    sa.Column('entity_b_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('positive_signals', sa.JSON(), nullable=False),
    sa.Column('negative_signals', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('relationship_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'entity_a_id', 'entity_b_id', name='uq_correlation_pair')
    )
    with op.batch_alter_table('correlations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correlations_case_id'), ['case_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('search_execution_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('temporality', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_execution_id'], ['search_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'fingerprint', name='uq_evidence_case_fingerprint')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_entity_id'), ['entity_id'], unique=False)

    op.create_table('relationship_evidence',
    sa.Column('relationship_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_evidence')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_entity_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('correlations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlations_case_id'))

    op.drop_table('correlations')
    with op.batch_alter_table('search_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_executions_status'))
        batch_op.drop_index(batch_op.f('ix_search_executions_provider'))
        batch_op.drop_index(batch_op.f('ix_search_executions_case_id'))

    op.drop_table('search_executions')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_target_entity_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_source_entity_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_case_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('pivots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pivots_case_id'))

    op.drop_table('pivots')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_case_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('case_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_inputs_case_id'))

    op.drop_table('case_inputs')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_case_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_case_type')
        batch_op.drop_index(batch_op.f('ix_entities_case_id'))

    op.drop_table('entities')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_case_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))

    op.drop_table('cases')
    # ### end Alembic commands ###
