"""análises de IA (interpretação DERIVED, nunca evidência)

Revision ID: 0003_ai
Revises: 0002_jobs
Create Date: 2026-09-29 18:45:51.383020
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0003_ai'
down_revision = '0002_jobs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_annotations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_kind', sa.String(length=10), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_refs', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('review', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_annotations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_annotations_operation'), ['operation'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_annotations_operation'))
        batch_op.drop_index(batch_op.f('ix_ai_annotations_case_id'))

    op.drop_table('ai_annotations')
    # ### end Alembic commands ###
